# Compare manually identified Owenmore turbidity events to positive CANARY events #

# Load packages
library(here)
library(data.table) 
library(dplyr)


# This section of the code combines the manually identified events by the user with the output for each of the 96 algorithm files produced by CANARY into one dataframe, creating 96 new .csv files.  The files are saved into six directories (folders) in the same file format as the CANARY output with the file name structure: sitedate_algorithm type_algorithm details_algorithm number.  These files are saved in the directory associated with that data which is specified by the user by amending the code for the identifier in section 8.12.  In this example, the data to be processed was placed in the directory called Data1 and the identifier set as follows #data_set_identifier<-"Data1/".  Where mutiple datasets are to be processed the user places each dataset in it's own directory, e.g. Data1, Data2, Data3 etc and updates the code for data_set_identifier when running each dataset.  The code automatically creates a directory in Output_Files for each dataset specified and ran through the code e.g. Output_Files/Data1, Output_Files/Data2 etc. 
# The output for step 8 comparing manually identified and CANARY events is saved in 08 Manually compare events to CANARY events/Output_files.


# Specify the directory where the "manually verified event data" in located.
 
# The path for this directory should be given relative to the project directory.
# Set the top directory for this step
ManVer_file_top_directory<-"06 Manually Identify Potential Water Quality Events/Output_Files/"

# This identifier is used to select the "manually verified event dataset" to be processed.
data_set_identifier<-"Data1/"

# Sets up the full path to the "manually verified event data".
ManVer_file_directory<-paste0(ManVer_file_top_directory,data_set_identifier)
(ManVer_file<-list.files(ManVer_file_directory,pattern='ManVer_TurbEvent'))
ManVer_file_full_path<-paste0(ManVer_file_directory,ManVer_file)

# Load the "manually verified event data" and format the dataframe.
 
# Load the "manually verified event data".
ManVer_TurbEvent<-fread(ManVer_file_full_path,header=T,stringsAsFactors = F, select = c("DateTime","Turbidity","Verified_OW_Event_Alarm"))
str(ManVer_TurbEvent)

# Change DateTime from chr to Date (as.POSIXct stores both a date and time with an associated time zone)
ManVer_TurbEvent$DateTime<-as.POSIXct(ManVer_TurbEvent$DateTime, format = "%d/%m/%Y %H:%M", tz="UTC")
str(ManVer_TurbEvent)

# Rename to TIME_STEP to match the Owenmore CANARY File
ManVer_TurbEvent<- ManVer_TurbEvent%>% rename(TIME_STEP = DateTime)

# Get list of directory names in the folder "07 EPA CANARY Event Detection"
## Each directory is associated with a different configuration of CANARY.
## Within each directory are output files generated by various versions of the algorithm.
## The path for top_dir should be given relative to the project directory.
output_file_top_directory<-"07_EPA_CANARY_Event_Detection/Output_Files/"

output_file_full_path<-paste0(output_file_top_directory,data_set_identifier)

# List directories but not sub-directories.
(directory_list<-list.dirs(output_file_full_path,recursive=FALSE))

ID_String<-vector(mode="character",length=length(directory_list))
for (i in 1:length(directory_list)){
  
  ID_String[i]<-paste0("_L",sub(".*_L","",directory_list[i]))
}

# Load the Owenmore CANARY file From 07 EPA CANARY Event Detection Folder
## Now, step through each folder and locate the csv files for each algorithm.
## Loop over the directories
for (i in 1:length(directory_list)){
  
  # List all files in each parent directory, in turn.
  (files_list<-list.files(directory_list[i],pattern='alg'))   #list all files in specified directory (directory_list[i]) that match pattern 'alg'.
  alg_ver<-vector(mode="character",length=length(files_list)) # initialise two character vectors, alg_ver and Output_filename_string, to store information about the files.
  Output_filename_string<-vector(mode="character",length=length(files_list))
  
  # Loop through each file in the files_list  
  for (j in 1:length(files_list)){
    
    
    # Put together the input filename and directory it is in.
    input_filename_string<-paste0(directory_list[i],'/',files_list[j])
    
    # Read each of the "CANARY Event Detection" data files into a dataframe called "Input_Data"
    Input_Data<-fread(input_filename_string, header=T, stringsAsFactors = F,
                      select = c("TIME_STEP","P_Event"))
    
    
    # Put together string name for output file.
    
    # First get the "algorithm version from each filename.
    # It's found by taking the part of the filename after the word "details" without the last 5 characters.
    
    alg_ver[j]<-str_sub(sub(".*details-","",files_list[j]), end=-5)
    
    # Setup the output filename.
    #(output_filename_string<-paste0("CANARYOwenmore",ID_String[i],alg_ver))
    
    #str(Input_Data)
    
    #Change TIME_STEP from chr to Date 
    Input_Data$TIME_STEP<-as.POSIXct(Input_Data$TIME_STEP, format = "%d/%m/%Y %H:%M", tz="UTC")
    
    # Change any negative values in CANARYOwenmoreAlg1 P_Event to absolute values to facilitate matching query
    Input_Data$`P_Event`<-abs(Input_Data$`P_Event`)
    
    
    
    # A column containing the "manually verified event data" is added to the "CANARY" dataframe and saved into a new...
    #... data frame called "Combined Data".
    
    Combined_Data<-merge(Input_Data,ManVer_TurbEvent,by="TIME_STEP")
    
    #(which(is.na(Input_Data), arr.ind=TRUE))
    
    # View the first few rows and the structure of the combined dataframe
    #head(Combined_Data)
    #str(Combined_Data)
    
    # Export this data table as.csv file
    here() # indicates the working directory
    Combined_Data$TIME_STEP<-format(Combined_Data$TIME_STEP) # this prevents 00:00:00 being removed from Timestamps
    
    
    # Now setup directory and filename for saving the combined data file. 
    
    Output_directory_string<-paste0("08 Manually compare events to CANARY events/Output_Files/",data_set_identifier)
    Output_subdirectory_string<-paste0("Output_Files_",ID_String[i],"/")
    
    Output_directory_string_complete<-paste0(Output_directory_string,Output_subdirectory_string)
    
    # Extract the location and date range information from the "manually verified event data" filename.
    # i.e, take the first part of the filename before the "_ManVer_TurbEvents...." 
    
    Location_and_Date_Range_ID_String<-sub("\\_M.*","",ManVer_file)
    
    Output_filename_string[j]<-paste0(Location_and_Date_Range_ID_String,ID_String[i],alg_ver[j],".csv")
    
    (Output_file_path_and_name<-paste0(Output_directory_string,Output_subdirectory_string,Output_filename_string[j]))
    
    if (!dir.exists(Output_directory_string_complete)) dir.create(Output_directory_string_complete, recursive = TRUE)
    
    write.csv(Combined_Data,Output_file_path_and_name, row.names=FALSE)
    if (j==1){
      # Only print this message once per processed directory.
      cat("Writing data to file:\n",Output_file_path_and_name,"\n")}
  }
}

